/**
 * Fallback CoinMarketCap ranking (rank, CMC symbol, name), used only when the live
 * CMC listing can't be reached. Snapshot taken 2026-09-26, pre-filtered to coins
 * with an active Binance USDT spot pair (stablecoins excluded).
 */
export const CMC_SNAPSHOT: ReadonlyArray<readonly [rank: number, symbol: string, name: string]> = [
  [1, "BTC", "Bitcoin"],
  [2, "ETH", "Ethereum"],
  [4, "BNB", "BNB"],
  [5, "XRP", "XRP"],
  [7, "SOL", "Solana"],
  [8, "TRX", "TRON"],
  [9, "ZEC", "Zcash"],
  [10, "HYPE", "Hyperliquid"],
  [11, "DOGE", "Dogecoin"],
  [12, "LINK", "Chainlink"],
  [14, "ADA", "Cardano"],
  [16, "XLM", "Stellar"],
  [17, "BCH", "Bitcoin Cash"],
  [18, "NEAR", "NEAR Protocol"],
  [19, "UNI", "Uniswap"],
  [20, "LTC", "Litecoin"],
  [23, "SUI", "Sui"],
  [24, "AVAX", "Avalanche"],
  [27, "HBAR", "Hedera"],
  [28, "GRAM", "Gram (prev. Toncoin)"],
  [29, "TAO", "Bittensor"],
  [30, "SHIB", "Shiba Inu"],
  [33, "ENA", "Ethena"],
  [36, "ONDO", "Ondo"],
  [40, "AAVE", "Aave"],
  [42, "DOT", "Polkadot"],
  [43, "PUMP", "Pump.fun"],
  [44, "ASTER", "Aster"],
  [45, "PAXG", "PAX Gold"],
  [46, "WLFI", "World Liberty Financial"],
  [47, "SKY", "Sky"],
  [48, "PEPE", "Pepe"],
  [49, "WLD", "Worldcoin"],
  [50, "ICP", "Internet Computer"],
  [52, "ETC", "Ethereum Classic"],
  [53, "ARB", "Arbitrum"],
  [55, "MORPHO", "Morpho"],
  [58, "QNT", "Quant"],
  [59, "POL", "Polygon (prev. MATIC)"],
  [62, "JUP", "Jupiter"],
  [64, "ALGO", "Algorand"],
  [65, "RENDER", "Render"],
  [67, "JST", "JUST"],
  [69, "ATOM", "Cosmos"],
  [70, "FIL", "Filecoin"],
  [71, "AERO", "Aerodrome Finance"],
  [72, "CAKE", "PancakeSwap"],
  [73, "DASH", "Dash"],
  [74, "VET", "VeChain"],
  [75, "INJ", "Injective"],
  [76, "APT", "Aptos"],
  [77, "ETHFI", "ether.fi"],
  [80, "PENGU", "Pudgy Penguins"],
  [82, "STX", "Stacks"],
  [83, "TRUMP", "OFFICIAL TRUMP"],
  [84, "PYTH", "Pyth Network"],
  [85, "ZRO", "LayerZero"],
  [86, "FET", "Artificial Superintelligence Alliance"],
  [87, "SEI", "Sei"],
  [88, "NEXO", "Nexo"],
  [89, "CRV", "Curve DAO Token"],
  [90, "RAY", "Raydium"],
  [91, "VIRTUAL", "Virtuals Protocol"],
  [96, "TIA", "Celestia"],
  [97, "PENDLE", "Pendle"],
  [101, "NIGHT", "Midnight"],
  [102, "FF", "Falcon Finance"],
  [103, "LDO", "Lido DAO"],
  [104, "BTT", "BitTorrent [New]"],
  [105, "XTZ", "Tezos"],
  [106, "KITE", "Kite"],
  [107, "OP", "Optimism"],
  [108, "XPL", "Plasma"],
  [109, "IMX", "Immutable"],
  [110, "SUN", "Sun [New]"],
  [111, "BONK", "Bonk"],
  [114, "DCR", "Decred"],
  [115, "LUNC", "Terra Classic"],
  [116, "STRK", "Starknet"],
  [117, "JTO", "Jito"],
  [118, "GRT", "The Graph"],
  [119, "AR", "Arweave"],
  [120, "GNO", "Gnosis"],
  [121, "ENS", "Ethereum Name Service"],
  [122, "CFX", "Conflux"],
  [124, "FLOKI", "FLOKI"],
  [125, "SYRUP", "Maple Finance"],
  [126, "2Z", "DoubleZero"],
  [127, "TWT", "Trust Wallet Token"],
  [128, "KMNO", "Kamino"],
  [129, "EIGEN", "EigenCloud"],
  [130, "WIF", "dogwifhat"],
  [131, "COMP", "Compound"],
  [133, "IOTA", "IOTA"],
  [134, "THETA", "Theta Network"],
  [135, "RUNE", "THORChain"],
  [136, "JASMY", "JasmyCoin"],
  [137, "ZAMA", "Zama"],
  [138, "KAIA", "Kaia"],
  [141, "AXS", "Axie Infinity"],
];
